
// Auto-generated by AutoPilot on 29-07-2023 at 03:32:39

const express = require('express');
const router = express.Router();

//Retrieve 5 shows from 1990-2000
router.get("/retro", (req, res) => {
    let shows = ["The Fresh Prince of Bel-Air", "Friends", "Seinfeld", "Frasier", "The X-Files"];
    res.json(shows);
});

module.exports = router;